export const ErrorCode = {
  // Shop
  SHOP_SLUG_MISSING: "SHOP_SLUG_MISSING",
  SHOP_ID_MISSING: "SHOP_ID_MISSING",
  SHOP_NOT_FOUND: "SHOP_NOT_FOUND",

  // Category
  CATEGORY_ID_MISSING: "CATEGORY_ID_MISSING",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  // Product
  PRODUCT_SLUG_MISSING: "PRODUCT_SLUG_MISSING",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCTS_NOT_FOUND: "PRODUCTS_NOT_FOUND",

  // Testimonials
  TESTIMONIALS_NOT_FOUND: "TESTIMONIALS_NOT_FOUND",

  // Sections
  SECTIONS_MISSING: "SECTIONS_MISSING",

  GENERAL_ERROR: "SOME PROPERTIS ARE MISSING",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
