export type GeorgiaCity = {
  name_ka: string;
  name_en: string;
};

export const GEORGIA_CITIES: GeorgiaCity[] = [
  { name_ka: "თბილისი", name_en: "Tbilisi" },
  { name_ka: "აბაშა", name_en: "Abasha" },
  { name_ka: "ამბროლაური", name_en: "Ambrolauri" },
  { name_ka: "ახალქალაქი", name_en: "Akhalkalaki" },
  { name_ka: "ახალციხე", name_en: "Akhaltsikhe" },
  { name_ka: "ახმეტა", name_en: "Akhmeta" },
  { name_ka: "ბათუმი", name_en: "Batumi" },
  { name_ka: "ბაღდათი", name_en: "Baghdati" },
  { name_ka: "ბოლნისი", name_en: "Bolnisi" },
  { name_ka: "ბორჯომი", name_en: "Borjomi" },
  { name_ka: "გარდაბანი", name_en: "Gardabani" },
  { name_ka: "გორი", name_en: "Gori" },
  { name_ka: "გურჯაანი", name_en: "Gurjaani" },
  { name_ka: "დედოფლისწყარო", name_en: "Dedoplistskaro" },
  { name_ka: "დმანისი", name_en: "Dmanisi" },
  { name_ka: "დუშეთი", name_en: "Dusheti" },
  { name_ka: "ვალე", name_en: "Vale" },
  { name_ka: "ვანი", name_en: "Vani" },
  { name_ka: "ზესტაფონი", name_en: "Zestaponi" },
  { name_ka: "ზუგდიდი", name_en: "Zugdidi" },
  { name_ka: "თეთრიწყარო", name_en: "Tetritskaro" },
  { name_ka: "თელავი", name_en: "Telavi" },
  { name_ka: "თერჯოლა", name_en: "Terjola" },
  { name_ka: "კასპი", name_en: "Kaspi" },
  { name_ka: "ლაგოდეხი", name_en: "Lagodekhi" },
  { name_ka: "ლანჩხუთი", name_en: "Lanchkhuti" },
  { name_ka: "მარნეული", name_en: "Marneuli" },
  { name_ka: "მარტვილი", name_en: "Martvili" },
  { name_ka: "მცხეთა", name_en: "Mtskheta" },
  { name_ka: "ნინოწმინდა", name_en: "Ninotsminda" },
  { name_ka: "ოზურგეთი", name_en: "Ozurgeti" },
  { name_ka: "ონი", name_en: "Oni" },
  { name_ka: "რუსთავი", name_en: "Rustavi" },
  { name_ka: "საგარეჯო", name_en: "Sagarejo" },
  { name_ka: "სამტრედია", name_en: "Samtredia" },
  { name_ka: "საჩხერე", name_en: "Sachkhere" },
  { name_ka: "სენაკი", name_en: "Senaki" },
  { name_ka: "სიღნაღი", name_en: "Sighnaghi" },
  { name_ka: "ტყიბული", name_en: "Tkibuli" },
  { name_ka: "ფოთი", name_en: "Poti" },
  { name_ka: "ქარელი", name_en: "Kareli" },
  { name_ka: "ქობულეთი", name_en: "Kobuleti" },
  { name_ka: "ქუთაისი", name_en: "Kutaisi" },
  { name_ka: "ყვარელი", name_en: "Kvareli" },
  { name_ka: "ცაგერი", name_en: "Tsageri" },
  { name_ka: "წალენჯიხა", name_en: "Tsalenjikha" },
  { name_ka: "წალკა", name_en: "Tsalka" },
  { name_ka: "წნორი", name_en: "Tsnori" },
  { name_ka: "წყალტუბო", name_en: "Tskaltubo" },
  { name_ka: "ჭიათურა", name_en: "Chiatura" },
  { name_ka: "ხაშური", name_en: "Khashuri" },
  { name_ka: "ხობი", name_en: "Khobi" },
  { name_ka: "ხონი", name_en: "Khoni" },
  { name_ka: "ჯვარი", name_en: "Jvari" },
];
